name: productivity_mobile
description: "Productivity mobile"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cookie_jar: ^4.0.8
  path_provider: ^2.1.5
  flutter_quill: ^10.8.5
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^8.0.2
  cached_network_image: ^3.4.1
  infinite_widgets: ^2.0.2
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  skeletonizer: ^1.4.2
  toastification: ^2.3.0
  dio: ^5.7.0
  flutter_native_splash: ^2.4.2
  dio_cookie_manager: ^3.1.1
  rename_app: ^1.6.1
  flutter_widget_from_html: ^0.15.2
  flutter_lorem: ^2.0.0
  side_effect_bloc: ^1.0.0
  flutter_form_bloc:
    git:
      url: https://github.com/BojanDo/form_bloc.git
      ref: master
      path: packages/flutter_form_bloc
  colorize_text_avatar: ^1.0.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  faker: ^2.2.0
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  event_bus: ^2.0.1
  open_filex: ^4.5.0
  ambient_light: ^0.0.5
  file_picker: ^8.1.7
  multi_select_flutter: ^4.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"


flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#ffffff"
  image: assets/icon/splash_icon.png

  android_12:
    color: "#ffffff"
    image: assets/icon/splash_icon.png


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

